### ISSUE TITLE
v2ray节点无法科学上网

### ISSUE THREAD

**Issue by liziru** [ruoyizhou/OpenWRT-For-Pi#11]
你好，多谢你的工作。我基于你提供的nanopi neo2固件做软路由，在添加了v2ray节点后（该节点测试pc客户端可用），测试谷歌仍然失败。我做了很多尝试依旧无效。麻烦你能提供一些指导吗？（估计xray也不行）
![image](https://user-images.githubusercontent.com/34911790/112740831-b810ee00-8fb2-11eb-97d6-9559fd696b9f.png)
![image](https://user-images.githubusercontent.com/34911790/112740847-d545bc80-8fb2-11eb-8755-8114559a3070.png)

**Comment by liziru** [comment]
![image](https://user-images.githubusercontent.com/34911790/112740880-01613d80-8fb3-11eb-8c7d-cdc0e2702935.png)
@ruoyizhou

**Comment by ruoyizhou** [comment]
> 你好，多谢你的工作。我基于你提供的nanopi neo2固件做软路由，在添加了v2ray节点后（该节点测试pc客户端可用），测试谷歌仍然失败。我做了很多尝试依旧无效。麻烦你能提供一些指导吗？（估计xray也不行）
> ![image](https://user-images.githubusercontent.com/34911790/112740831-b810ee00-8fb2-11eb-97d6-9559fd696b9f.png)
> ![image](https://user-images.githubusercontent.com/34911790/112740847-d545bc80-8fb2-11eb-8755-8114559a3070.png)

你好，这个问题测试的确存在，之后我会更新固件。由于插件并非本人开发，无法给你帮助。
