### ISSUE TITLE
能否加一个pt工具Transmission

### ISSUE THREAD

**Issue by seaxp** [ruoyizhou/OpenWRT-For-Pi#9]
Nano Pi r1 受到CPU等性能限制，被其他软路由设备替代了，在家里用处不大，吃灰半年了，想用来挂载一个usb硬盘刷pt挂机用，看能否增加一个pt工具Transmission。谢谢！

**Comment by laoliudada** [comment]
> Nano Pi r1 受到CPU等性能限制，被其他软路由设备替代了，在家里用处不大，吃灰半年了，想用来挂载一个usb硬盘刷pt挂机用，看能否增加一个pt工具Transmission。谢谢！

Transmission 工具最新版的固件里面是有的，我在列表里忘写了。不过NanoPi R1 型号的固件我没有编译。
